### ISSUE TITLE
No contextual menu entries for requests in Proxy History and Sitemap

### ISSUE THREAD

**Issue by ngregoire** [hackvertor/hackvertor#79]
The title says it all ;-)
Tested with Hackvertor 1.7.38 and Burp Pro EA 2023.3-19417 (JDK 19)

**Comment by hackvertor** [comment]
I think this was a bug in Burp as it's magically fixed in v2023.3.3

**Comment by ngregoire** [comment]
I tried in EA 2023.4.2-20225 (with Hackvertor being the only loaded extension) and the behavior described above still exists

**Comment by ngregoire** [comment]
FYI, EA 2023.6.1 is still affected

**Comment by ngregoire** [comment]
FYI, EA 2023.10.1 is still affected

**Comment by hackvertor** [comment]
Ah sorry I'll look into this

**Comment by ngregoire** [comment]
It seems that only requests are affected. Responses are OK, as the Hackvertor contextual menu appears.

**Comment by ngregoire** [comment]
FYI this issue still exists (tested today with Burp Suite Pro 2023.10.3.4-24713 and Hackvertor v1.7.49)

**Comment by ngregoire** [comment]
I confirm the bug is fixed (tested with Hackvertor v1.8.9 and Burp Suite Pro v2023.11.1.2). Good job!
